# Generated by Django 5.1.2 on 2024-11-13 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=15, unique=True)),
                ('color', models.CharField(default='33, 10, 230', max_length=13)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('text', models.CharField(max_length=70)),
                ('rating', models.IntegerField(default=0)),
                ('answer_count', models.IntegerField(default=0)),
                ('creation_date', models.DateField()),
                ('author', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='app.profile')),
                ('tags', models.ManyToManyField(blank=True, to='app.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=70)),
                ('rating', models.IntegerField(default=0)),
                ('correct', models.BooleanField(default=False)),
                ('author', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('on_question_id', models.ForeignKey(db_column='question_id', on_delete=django.db.models.deletion.CASCADE, to='app.question')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerLike',
            fields=[
                ('like_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_of_like', models.CharField(choices=[('L', 'Like'), ('D', 'Dislike')], max_length=1)),
                ('answer', models.ForeignKey(db_column='answer_id', on_delete=django.db.models.deletion.CASCADE, to='app.answer')),
                ('author', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='app.profile')),
            ],
            options={
                'unique_together': {('author', 'answer')},
            },
        ),
        migrations.CreateModel(
            name='QuestionLike',
            fields=[
                ('like_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_of_like', models.CharField(choices=[('L', 'Like'), ('D', 'Dislike')], max_length=1)),
                ('author', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='app.profile')),
                ('question', models.ForeignKey(db_column='question_id', on_delete=django.db.models.deletion.CASCADE, to='app.question')),
            ],
            options={
                'unique_together': {('author', 'question')},
            },
        ),
    ]
